services:
  - type: web
    name: baby-steps-demo-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000